### ISSUE TITLE
Dependency versions are not properly parsed

### ISSUE THREAD

**Issue by axel-op** [dart-lang/pana#1047]
The versions of the dependencies are not correctly parsed during package resolution.

The reason is that in `pkg_resolution.dart`, the regular expression used to parse the PubEntry content is outdated, resulting in an empty `pkgVersions` map.

Stacktrace:

```console
SEVERE     Problem with `dart pub upgrade`
           Bad state: For [xxx], the parsed version null did not match the locked version 3.0.0+2.
           #0      _validateLockedVersions.<anonymous closure> (package:pana/src/pkg_resolution.dart:224:11)
           #1      SplayTreeMap.forEach (dart:collection/splay_tree.dart:604:8)
           #2      _validateLockedVersions (package:pana/src/pkg_resolution.dart:220:12)
           #3      createPkgResolution (package:pana/src/pkg_resolution.dart:206:5)
           #4      PackageContext.resolveDependencies (package:pana/src/package_context.dart:70:26)
           <asynchronous suspension>
           #5      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:149:27)
           <asynchronous suspension>
           #6      PackageAnalyzer.inspectDir.<anonymous closure> (package:pana/src/package_analyzer.dart:98:14)
           <asynchronous suspension>
           #7      withTempDir (package:pana/src/utils.dart:235:12)
           <asynchronous suspension>
           #8      main (file:///C:/Users/axelp/Documents/Git%20Repositories/pana/bin/pana.dart:173:19)
           <asynchronous suspension>
```

Pana version: 0.21.10
Dart SDK version: 2.17.0-229.0.dev (dev)

**Comment by isoos** [comment]
Could you please provide a reproducible example (either a public package or a detailed pubspec with the problem)?

**Comment by axel-op** [comment]
The problem is reproducible on packages with a pubspec containing a `dependencies` section.

For example, when running pana on [this package](https://github.com/SpinlockLabs/github.dart), I have the following output:

```console
INFO       Running `C:\tools\dart-sdk\bin\dart.exe --version`...
INFO       Running `flutter.bat --no-version-check --version --machine`...
INFO       Running `git rev-parse --show-toplevel`...
INFO       Running `C:\tools\dart-sdk\bin\dart.exe pub upgrade --verbose`...
SEVERE     Problem with `dart pub upgrade`
           Bad state: For async, the parsed version null did not match the locked version 2.8.2.
           #0      _validateLockedVersions.<anonymous closure> (package:pana/src/pkg_resolution.dart:221:11)
           #1      SplayTreeMap.forEach (dart:collection/splay_tree.dart:604:8)
           #2      _validateLockedVersions (package:pana/src/pkg_resolution.dart:217:12)
           #3      createPkgResolution (package:pana/src/pkg_resolution.dart:203:5)
           #4      PackageContext.resolveDependencies (package:pana/src/package_context.dart:70:26)
           <asynchronous suspension>
           #5      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:149:27)
           <asynchronous suspension>
           #6      PackageAnalyzer.inspectDir.<anonymous closure> (package:pana/src/package_analyzer.dart:98:14)     
           <asynchronous suspension>
           #7      withTempDir (package:pana/src/utils.dart:233:12)
           <asynchronous suspension>
           #8      main (file:///C:/Users/axelp/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pana-0.21.10/bin/pana.dart:173:19)
           <asynchronous suspension>
INFO       Analyzing package...
INFO       Running `C:\tools\dart-sdk\bin\dart.exe analyze --format machine lib`...
INFO       Running `C:\tools\dart-sdk\bin\dart.exe format --output=none --set-exit-if-changed C:\Users\axelp\AppData\Local\Temp\pana_2d2ff78e\.\lib`...
INFO       Running `C:\tools\dart-sdk\bin\dart.exe pub get .`...
INFO       Running `C:\tools\dart-sdk\bin\dart.exe pub outdated --json --up-to-date --no-dev-dependencies --no-dependency-overrides`...
```

OS: Windows
Pana version: 0.21.10
Dart SDK version: 2.17.0-229.0.dev (dev)

**Comment by jonasfj** [comment]
What does the output of `dart pub upgrade` look like?

**Comment by axel-op** [comment]
@jonasfj The output looks like that:

```console
MSG : Resolving dependencies...
MSG : * async 2.8.2 (was 2.8.2)
    | * charcode 1.3.1 (was 1.3.1)
    | * collection 1.15.0 (was 1.15.0) (1.16.0 available)
    | * http 0.13.4 (was 0.13.4)
    | * http_parser 4.0.0 (was 4.0.0)
    | * json_annotation 4.4.0 (was 4.4.0)
    | * meta 1.7.0 (was 1.7.0)
    | * path 1.8.1 (was 1.8.1)
    | * source_span 1.8.2 (was 1.8.2)
    | * string_scanner 1.1.0 (was 1.1.0)
    | * term_glyph 1.2.0 (was 1.2.0)
    | * typed_data 1.3.0 (was 1.3.0)
    | These packages are no longer being depended on:
    | - _fe_analyzer_shared 38.0.0
    | - analyzer 3.4.1
    | - archive 3.3.0
    | - args 2.3.0
```

**Comment by jonasfj** [comment]
Ah, so the change is that we want to handle:
```
    | * collection 1.15.0 (was 1.15.0) (1.16.0 available)
```

I think this is a bug.

We probably need to handle it in pana, since we are shipping with this bug.

Filed https://github.com/dart-lang/pub/issues/3372
