### ISSUE TITLE
Parse-codeproblem does not understand when analyzer writes: `Please report this at dartbug.com.`

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pana#1081]
Could not reproduce locally...

Error from logs:
```
pub.analyzer.pana: Failed (v0.21.12) - webinstats_flutter/0.0.2

Error:
    Invalid argument(s): Provided content does not align with expectations.
    `Please report this at dartbug.com.`

Stack:
    #0      parseCodeProblem (package:pana/src/code_problem.dart:65:5)
    #1      PackageContext.staticAnalysis.<anonymous closure> (package:pana/src/package_context.dart:121:25)
    #2      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
    #3      IterableNullableExtension.whereNotNull (package:collection/src/iterable_extensions.dart:583:25)
    #4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:186:26)
    #5      SetMixin.addAll (dart:collection/set.dart:57:23)
    #6      _CompactLinkedHashSet.addAll (dart:collection-patch/compact_hash.dart:973:11)
    #7      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:192:27)
    #8      Iterable.toSet (dart:core/iterable.dart:486:21)
    #9      PackageContext.staticAnalysis (package:pana/src/package_context.dart:123:14)
```

**Comment by isoos** [comment]
I think this may be related to https://github.com/dart-lang/sdk/issues/49272

**Comment by isoos** [comment]
We should probably report it nicely in the report output.
