### ISSUE TITLE
fix: `checkRemoteRepository` is not configurable and runs against the git root instead of the target directory

### ISSUE THREAD

**Issue by felangel** [dart-lang/pana#1106]
When I run `pana --no-warnings ./path/to/package` locally, I expect pana to only analyze the contents of the target directory.

Instead, `pana` will always clone the entire repository and perform checks against the repo. https://github.com/dart-lang/pana/blob/d52a5394d4987b533e515a60a29cecb2a305fdfe/lib/src/repository/check_repository.dart#L68 The checks should either still be scoped to just the target directory within the repo or the `checkRemoteRepository` option should be configurable.

Reproduction Sample:

1. `git clone https://github.com/VeryGoodOpenSource/dart_frog`
2. `cd dart_frog`
3. `pana --no-warnings ./packages/dart_frog`

Outputs:

```sh
$ pana --no-warning ./packages/dart_frog
INFO       Running `/Users/felix/fvm/versions/stable/bin/cache/dart-sdk/bin/dart --version`...
INFO       Running `flutter --no-version-check --version --machine`...
INFO       Running `git rev-parse --show-toplevel`...
INFO       Running `/Users/felix/fvm/versions/stable/bin/cache/dart-sdk/bin/dart pub get .`...
INFO       Running `/Users/felix/fvm/versions/stable/bin/cache/dart-sdk/bin/dart pub outdated --json --up-to-date --no-dev-dependencies --no-dependency-overrides`...
INFO       Analyzing package...
INFO       Running `/Users/felix/fvm/versions/stable/bin/cache/dart-sdk/bin/dart analyze --format machine lib`...
INFO       Running `git init`...
INFO       Running `git remote add origin https://github.com/VeryGoodOpenSource/dart_frog`...
INFO       Running `git remote show origin`...
INFO       Running `git fetch --depth 1 --no-recurse-submodules origin main`...
INFO       Running `git ls-tree -r --name-only --full-tree origin/main`...
INFO       Running `git show origin/main:bricks/create_dart_frog/__brick__/pubspec.yaml`...
SHOUT      Problem analyzing ./packages/dart_frog
           CheckedFromJsonException
           Could not create `Pubspec`.
           There is a problem with "name".
           type 'Null' is not a subtype of type 'String' in type cast
           #0      $checkedConvert (package:json_annotation/src/checked_helpers.dart:94:5)
           #1      $checkedCreate._checkedConvert (package:json_annotation/src/checked_helpers.dart:31:7)
           #2      _$PubspecFromJson.<anonymous closure> (package:pubspec_parse/src/pubspec.g.dart:16:26)
           #3      $checkedCreate.<anonymous closure> (package:json_annotation/src/checked_helpers.dart:36:22)
           #4      $checkedNew (package:json_annotation/src/checked_helpers.dart:54:23)
           #5      $checkedCreate (package:json_annotation/src/checked_helpers.dart:33:10)
           #6      _$PubspecFromJson (package:pubspec_parse/src/pubspec.g.dart:11:40)
           #7      new Pubspec.fromJson (package:pubspec_parse/src/pubspec.dart:139:18)
           #8      new Pubspec (package:pana/src/pubspec.dart:21:34)
           #9      new Pubspec.parseYaml (package:pana/src/pubspec.dart:25:7)
           #10     checkRepository.matchRepoPubspecYaml (package:pana/src/repository/check_repository.dart:116:32)
           <asynchronous suspension>
           #11     checkRepository (package:pana/src/repository/check_repository.dart:153:21)
           <asynchronous suspension>
           #12     checkPubspecUrls (package:pana/src/references/pubspec_urls.dart:56:30)
           <asynchronous suspension>
           #13     followsTemplate.checkPubspec (package:pana/src/report/template.dart:185:25)
           <asynchronous suspension>
           #14     followsTemplate (package:pana/src/report/template.dart:253:26)
           <asynchronous suspension>
           #15     createReport (package:pana/src/report/create_report.dart:42:5)
           <asynchronous suspension>
           #16     PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:251:15)
           <asynchronous suspension>
           #17     PackageAnalyzer.inspectDir.<anonymous closure> (package:pana/src/package_analyzer.dart:98:14)
           <asynchronous suspension>
           #18     withTempDir (package:pana/src/utils.dart:235:12)
           <asynchronous suspension>
           #19     main (file:///Users/felix/.pub-cache/hosted/pub.dartlang.org/pana-0.21.15/bin/pana.dart:174:19)
           <asynchronous suspension>
```

The analysis fails due to a malformed `Pubspec` (which I don't quite understand) but regardless, the pubspec being analyzed is `git show origin/main:bricks/create_dart_frog/__brick__/pubspec.yaml` which is outside of the target directory I specified.

**Comment by isoos** [comment]
Hm, looks like we should catch `CheckedFromJsonException`, which is apparently not a `FormatException` (although I think it should be.).

The remote repository check is independent of the local copy we are making. We do the local copy for various reasons, and won't change it, but handing the exception from the remote repository check should be the fix anyway. I'll put something together shortly...

**Comment by isoos** [comment]
#1108 handles this issue, in case you need it immediately. I'm not sure when this will hit a release, it is possible that it won't be done next week yet.

**Comment by felangel** [comment]
> #1108 handles this issue, in case you need it immediately. I'm not sure when this will hit a release, it is possible that it won't be done next week yet.

Thanks, really appreciate the quick response!
