### ISSUE TITLE
downloadPackage - ListMixin.firstWhere -- Bad state: No element

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#1154]
Probably because of a race condition, or caches weren't cleared, we should handle this gracefully.
```
pub.analyzer.pana: Failed (v0.21.20) - flutter_face_api_beta/0.0.72

Error:
    Bad state: No element

Stack:
    #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
    #1      downloadPackage (package:pana/src/download_utils.dart:48:10)
    <asynchronous suspension>
    #2      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
    <asynchronous suspension>
```

**Comment by sigurdm** [comment]
Closing as obsolete.
