### ISSUE TITLE
Bug in analyzer or in our processing?

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#366]
````
SEVERE     Could not create LibraryScanner
           Bad state: Expected exactly one context root, got [Instance of 'ContextRootImpl', Instance of 'ContextRootImpl', Instance of 'ContextRootImpl', Instance of 'ContextRootImpl', Instance of 'ContextRootImpl', Instance of 'ContextRootImpl']
           #0      new LibraryScanner (package:pana/src/library_scanner.dart:85:7)
           #1      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:222:30)
           <asynchronous suspension>
           #2      PackageAnalyzer.inspectPackage.<anonymous closure> (package:pana/src/package_analyzer.dart:85:22)
           <asynchronous suspension>
           #3      _rootRun (dart:async/zone.dart:1126:13)
           #4      _CustomZone.run (dart:async/zone.dart:1023:19)
           #5      _runZoned (dart:async/zone.dart:1518:10)
           #6      runZoned (dart:async/zone.dart:1465:12)
           #7      withLogger (package:pana/src/logging.dart:13:61)
           #8      PackageAnalyzer.inspectPackage (package:pana/src/package_analyzer.dart:71:12)
           <asynchronous suspension>
           #9      main (file:///Users/isoos/work/google/pub/pana/bin/pana.dart:147:34)
           <asynchronous suspension>
           #10     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
           #11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
````

The related code is:
````
    var contextLocator = new ContextLocator();
    var roots = contextLocator.locateRoots(includedPaths: [packagePath]);
    if (roots.length != 1) {
      throw new StateError('Expected exactly one context root, got $roots');
    }
````

**Comment by isoos** [comment]
Turns out that for select packages, the `package:analyzer` now finds multiple roots, the first one seems to be the package root, and additional ones are found e.g. in a subdirectory `testing/` (for e.g.  `package:dartdoc`).

Fix is underway.

**Comment by scheglov** [comment]
Yes, this is a feature - subdirectories might have different analysis options, dependencies, etc.
Analyzer returns all of them.
I'm sorry that this causes troubles.
