### ISSUE TITLE
how to use the library? Are there any examples of this?

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/pana#430]
I installed the package on my mac.

`pub global activate pana`

I want to run `pana` before I publish.

and I run next commnd in cli.
```
pana --flutter-sdk -s ~/IdeaProjects/flutter/plugin/flutter_oktoast
```

I get it.
```
SHOUT      Problem analyzing /Users/cai/IdeaProjects/flutter/plugin/flutter_oktoast
           FileSystemException: Cannot resolve symbolic links, path = '-s' (OS Error: No such file or directory, errno = 2)
           #0      FileSystemEntity.resolveSymbolicLinks.<anonymous closure> (dart:io/file_system_entity.dart:359:9)
           #1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
           #2      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
           #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
           #4      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
           #5      Future._completeWithValue (dart:async/future_impl.dart:486:5)
           #6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
           #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #9      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
           #10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

**Comment by isoos** [comment]
@CaiJingLong:

- `--flutter-sdk` needs a path to the SDK
- `-s` needs either `hosted` (default) or `path`

The command should be something like:

```
pana --flutter-sdk [the-path-to-flutter] -s path ~/IdeaProjects/flutter/plugin/flutter_oktoast
```

**Comment by CaiJingLong** [comment]
Thanks.
If possible, it is recommended that there is a complete sample code in readme.
