### ISSUE TITLE
Handle exception that are caused by the package content.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#445]

**Comment by isoos** [comment]
Example:

```
 #0      Loader._loadMapping (package:yaml/src/loader.dart:167:9)
    #1      Loader._loadNode (package:yaml/src/loader.dart:86:16)
    #2      Loader._loadDocument (package:yaml/src/loader.dart:62:20)
    #3      Loader.load (package:yaml/src/loader.dart:54:20)
    #4      loadYamlDocument (package:yaml/yaml.dart:51:25)
    #5      loadYamlNode (package:yaml/yaml.dart:42:5)
    #6      loadYaml (package:yaml/yaml.dart:34:5)
    #7      new Pubspec.parseYaml (package:pana/src/pubspec.dart:31:41)
    #8      new Pubspec.parseFromDir (package:pana/src/pubspec.dart:27:20)
    #9      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:119:27)
```

**Comment by isoos** [comment]
Rephrasing the requirement, as in general we don't want to throw exception on the package-content issues, rather report them in the suggestions and/or logs.
