### ISSUE TITLE
Error scanning direct libraries: NoSuchMethodError

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#617]
Stack trace from production, on package:keyboard_utils version 1.2.0
```
Error:
    NoSuchMethodError: The getter 'element' was called on null.
    Receiver: null
    Tried calling: element

Stack:
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      LibraryScanner._getLibraryElement (package:pana/src/library_scanner.dart:255:24)
    <asynchronous suspension>
    #2      LibraryScanner._parseLibs (package:pana/src/library_scanner.dart:221:21)
    <asynchronous suspension>
    #3      LibraryScanner._scanPackage (package:pana/src/library_scanner.dart:211:19)
    <asynchronous suspension>
    #4      LibraryScanner.scanDirectLibs (package:pana/src/library_scanner.dart:105:57)
    #5      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:288:48)
    #6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #7      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #8      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #9      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #10     _rootRunUnary (dart:async/zone.dart:1134:38)
    #11     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #12     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #14     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #15     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
    #17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
    #18     ToolEnvironment.runUpgrade (package:pana/src/sdk_env.dart)
    #19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #20     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #21     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #22     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #23     _rootRunUnary (dart:async/zone.dart:1134:38)
    #24     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #25     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #27     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #28     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #29     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
    #30     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
    #31     ToolEnvironment._restorePubspecYaml (package:pana/src/sdk_env.dart)
    #32     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #33     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #34     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #35     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #36     _rootRunUnary (dart:async/zone.dart:1134:38)
    #37     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #38     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #40     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #41     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #42     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
    #43     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #44     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #45     _rootRun (dart:async/zone.dart:1126:13)
    #46     _CustomZone.run (dart:async/zone.dart:1023:19)
    #47     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #48     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #49     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
    #50     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
    #51     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
    #52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by jonasfj** [comment]
Only package:keyboard_utils version 1.2.0 seems to be affected.

**Comment by jonasfj** [comment]
Also causes: "Error scanning transitive libraries Error: NoSuchMethodError"

**Comment by sigurdm** [comment]
It seems there's trouble with a file with a space in its name.

**Comment by isoos** [comment]
Reported the issue with a code to reproduce in https://github.com/dart-lang/sdk/issues/40974

**Comment by isoos** [comment]
The library in the original stacktrace is no longer in use.
