### ISSUE TITLE
unable to locate the input directory

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#630]
From logs:
```
pub.dartdoc.runner/myfatoorah_flutter/1.0.2: Error while running dartdoc for myfatoorah_flutter 1.0.2.
exitCode: 255
stdout: parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/utils/MFAPILanguage.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/utils/MFMobileISO.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/utils/MFCurrencyISO.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/utils/MFNotificationOption.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/utils/MFResult.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/utils/AppConstants.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/utils/MFKeyType.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/canceltoken/SDKCancelTokenResponse.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/initpayment/SDKInitiatePaymentResponse.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/initpayment/MFInitiatePaymentRequest.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/MyBaseResponse.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/directpayment/SDKDirectPaymentResponse.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/directpayment/MFCardInfo.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/directpayment/MFDirectPaymentResponse.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/sendpayment/SDKSendPaymentResponse.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/sendpayment/MFSendPaymentRequest.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/executepayment/MFExecutePaymentRequest.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/executepayment/SDKExecutePaymentResponse.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/paymentstatus/MFPaymentStatusRequest.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/paymentstatus/SDKPaymentStatusResponse.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/cancelrecurring/SDKCancelRecurringResponse.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/MFError.dart...
parsing /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/myfatoorah_flutter.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/collection/collection.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/developer/developer.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/internal/internal.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/_interceptors/interceptors.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/io/io.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/convert/convert.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/async/async.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/typed_data/typed_data.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/_empty.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/js_util/js_util_dart2js.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/html/html_dart2js.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/math/math.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/core/core.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/_http/http.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/ui/ui.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/js/js_dart2js.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/ffi/ffi.dart...
parsing /flutter/bin/cache/pkg/sky_engine/lib/wasm/wasm.dart...
stderr: Documenting myfatoorah_flutter...
Unhandled exception:
fatal error: unable to locate the input directory at /tmp/pub-dartlang-dartdocRTLWMR/pkg/lib/model/cancelRecurring.
#0      new PackageMeta.fromDir (package:dartdoc/src/package_meta.dart:120:7)
#1      new PackageMeta.fromFilename (package:dartdoc/src/package_meta.dart:109:24)
#2      PackageBuilder._packageMetasForFiles (package:dartdoc/src/model/package_builder.dart:221:29)
#3      PackageBuilder._parseLibraries (package:dartdoc/src/model/package_builder.dart:260:17)
<asynchronous suspension>
#4      PackageBuilder.getLibraries (package:dartdoc/src/model/package_builder.dart:386:11)
#5      PackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:50:11)
#6      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#7      PackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:41:41)
#8      Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:154:26)
#9      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#10     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:151:42)
#11     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:194:43)
#12     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#13     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:191:38)
#14     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:24:33)
#15     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     Dartdoc.fromContext (package:dartdoc/dartdoc.dart)
#23     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#28     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#29     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#30     initHtmlGenerator (package:dartdoc/src/generator/html_generator.dart)
#31     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#36     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#37     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#38     Templates._create (package:dartdoc/src/generator/templates.dart)
#39     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#40     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#41     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#42     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#43     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#44     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#45     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#46     Templates._create._loadTemplate (package:dartdoc/src/generator/templates.dart)
#47     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#51     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#52     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#53     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#54     loadAsString (package:dartdoc/src/generator/resource_loader.dart)
#55     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#60     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#61     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#62     loadAsBytes (package:dartdoc/src/generator/resource_loader.dart)
#63     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#64     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#65     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#66     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#67     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#68     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#69     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#70     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#71     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#72     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by sigurdm** [comment]
Closing as obsolete.
