### ISSUE TITLE
Invalid argument(s): Could not find package dir of analyzer

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#675]
**From logs**
```
"pub.analyzer.pana: Failed (v0.13.10) - built_stream_generator/1.0.9

Error:
    Invalid argument(s): Could not find package dir of kernel

Stack:
    #0      _PubspecCache._packageDir (package:pana/src/tag_detection.dart:324:7)
    #1      _PubspecCache.pubspecOfPackage.<anonymous closure> (package:pana/src/tag_detection.dart:345:35)
    #2      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
    #3      _PubspecCache.pubspecOfPackage (package:pana/src/tag_detection.dart:344:26)
    #4      _DeclaredFlutterPlatformDetector._declaredFlutterPlatforms.<anonymous closure> (package:pana/src/tag_detection.dart:524:36)
    #5      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
    #6      _DeclaredFlutterPlatformDetector._declaredFlutterPlatforms (package:pana/src/tag_detection.dart:522:35)
    #7      new _PlatformViolationFinder.<anonymous closure> (package:pana/src/tag_detection.dart:567:18)
    #8      _PathFinder.findPath (package:pana/src/tag_detection.dart:134:34)
    #9      _PathFinder.findViolation (package:pana/src/tag_detection.dart:148:39)
    #10     _PlatformViolationFinder._findPlatformViolation (package:pana/src/tag_detection.dart:582:59)
    #11     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
    #12     ListIterable.firstWhere (dart:_internal/iterable.dart:102:19)
    #13     Tagger.flutterPlatformTags (package:pana/src/tag_detection.dart:870:14)
    #14     PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:340:16)
    #15     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #16     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #17     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #18     _rootRunUnary (dart:async/zone.dart:1192:38)
    #19     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #20     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
    #21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
    #22     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
    #23     Future._completeWithValue (dart:async/future_impl.dart:526:5)
    #24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
    #25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
    #26     PackageAnalyzer._pkgAnalyze (package:pana/src/package_analyzer.dart)
    #27     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #28     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #29     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #30     _rootRunUnary (dart:async/zone.dart:1192:38)
    #31     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #32     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
    #33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
    #34     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
    #35     Future._completeWithValue (dart:async/future_impl.dart:526:5)
    #36     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
    #37     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
    #38     ToolEnvironment.runAnalyzer (package:pana/src/sdk_env.dart)
    #39     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #40     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #41     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #42     _rootRunUnary (dart:async/zone.dart:1192:38)
    #43     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #44     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
    #45     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
    #46     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
    #47     Future._completeWithValue (dart:async/future_impl.dart:526:5)
    #48     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
    #49     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #50     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #51     _rootRun (dart:async/zone.dart:1184:13)
    #52     _CustomZone.run (dart:async/zone.dart:1077:19)
    #53     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #54     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
    #55     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
    #56     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
    #57     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
    #58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by sigurdm** [comment]
`analyzer-0.39.2/lib/src/summary2/default_types_builder.dart imports` files from package:kernel that are not a dependency of  `analyzer-0.39.2`. I guess we should just fail the analysis.

**Comment by isoos** [comment]
> imports files from package:kernel that are not a dependency

I agree.
