### ISSUE TITLE
exception parsing SDK info on travis

### ISSUE THREAD

**Issue by pq** [dart-lang/pana#721]
See for example: https://travis-ci.org/github/dart-lang/linter/jobs/706601522

```dart
$ dart --version
Dart SDK version: 2.9.0-21.0.dev (dev) (Wed Jul 8 10:54:08 2020 +0200) on "linux_x64"

....

{"logName":"pana","level":"INFO","message":"Running `/home/travis/dart-sdk/bin/dart --version`..."}
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: [](1)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new DartSdkInfo.parse (package:pana/src/sdk_env.dart:494:38)
#2      ToolEnvironment._init (package:pana/src/sdk_env.dart:63:37)
<asynchronous suspension>
#3      ToolEnvironment.create (package:pana/src/sdk_env.dart:135:19)
<asynchronous suspension>
#4      PackageAnalyzer.create (package:pana/src/package_analyzer.dart:68:50)
#5      main (file:///home/travis/.pub-cache/hosted/pub.dartlang.org/pana-0.13.14/bin/pana.dart:129:44)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by pq** [comment]
Thanks @sigurdm!
