### ISSUE TITLE
findUrlIssues: type 'YamlList' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#732]
From logs

```
"pub.analyzer.pana: Failed (v0.13.15) - flutter_pagination_helper/1.0.0+2

Error:
    type 'YamlList' is not a subtype of type 'String' in type cast

Stack:
    #0      _followsTemplate.findUrlIssues (package:pana/src/create_report.dart:277:43)
    #1      _followsTemplate.checkPubspec (package:pana/src/create_report.dart:385:38)
    <asynchronous suspension>
    #2      _followsTemplate.checkPubspec (package:pana/src/create_report.dart)
    #3      _followsTemplate (package:pana/src/create_report.dart:512:44)
    <asynchronous suspension>
    #4      createReport (package:pana/src/create_report.dart:59:11)
    #5      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:442:21)
    <asynchronous suspension>
    #6      PackageAnalyzer.inspectPackage.<anonymous closure>.<anonymous closure> (package:pana/src/package_analyzer.dart:86:22)
    <asynchronous suspension>
    #7      PackageAnalyzer.inspectPackage.<anonymous closure>.<anonymous closure> (package:pana/src/package_analyzer.dart)
    #8      withTempDir (package:pana/src/download_utils.dart:238:20)
    <asynchronous suspension>
    #9      PackageAnalyzer.inspectPackage.<anonymous closure> (package:pana/src/package_analyzer.dart:83:14)
    #10     _rootRun (dart:async/zone.dart:1184:13)
    #11     _CustomZone.run (dart:async/zone.dart:1077:19)
    #12     _runZoned (dart:async/zone.dart:1619:10)
    #13     runZoned (dart:async/zone.dart:1539:10)
    #14     withLogger (package:pana/src/logging.dart:13:70)
    #15     PackageAnalyzer.inspectPackage (package:pana/src/package_analyzer.dart:81:12)
    #16     AnalyzerJobProcessor.process.analyze (package:pub_dev/analyzer/pana_runner.dart:82:31)
    <asynchronous suspension>
    #17     AnalyzerJobProcessor.process.analyze (package:pub_dev/analyzer/pana_runner.dart)
    #18     AnalyzerJobProcessor.process (package:pub_dev/analyzer/pana_runner.dart:104:36)
    <asynchronous suspension>
    #19     JobProcessor.run (package:pub_dev/job/job.dart:69:28)
    <asynchronous suspension>
    #20     JobMaintenance.run (package:pub_dev/job/job.dart:119:18)
    #21     _workerMain.<anonymous closure> (package:pub_dev/service/entrypoint/analyzer.dart:96:26)
    #22     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #24     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #25     _rootRunUnary (dart:async/zone.dart:1192:38)
    #26     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #27     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
    #28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
    #29     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
    #30     Future._completeWithValue (dart:async/future_impl.dart:526:5)
    #31     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
    #32     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
    #33     PopularityStorage.init (package:pub_dev/shared/popularity_storage.dart)
    #34     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #35     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #36     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #37     _rootRunUnary (dart:async/zone.dart:1192:38)
    #38     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #39     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
    #40     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
    #41     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
    #42     Future._completeWithValue (dart:async/future_impl.dart:526:5)
    #43     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
    #44     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
    #45     PopularityStorage.fetch (package:pub_dev/shared/popularity_storage.dart)
    #46     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #47     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #48     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #49     _rootRunUnary (dart:async/zone.dart:1192:38)
    #50     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #51     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
    #52     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
    #53     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
    #54     Future._complete (dart:async/future_impl.dart:516:7)
    #55     Stream.single.<anonymous closure> (dart:async/stream.dart:1337:20)
    #56     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #57     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #58     _rootRun (dart:async/zone.dart:1180:38)
    #59     _CustomZone.run (dart:async/zone.dart:1077:19)
    #60     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #61     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
    #62     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
    #63     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
    #64     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
    #65     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
    #66     _JsonStringDecoderSink.close (dart:convert-patch/convert_patch.dart:1492:11)
    #67     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:83:18)
    #68     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
    #69     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #70     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #71     _rootRun (dart:async/zone.dart:1180:38)
    #72     _CustomZone.run (dart:async/zone.dart:1077:19)
    #73     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #74     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
    #75     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
    #76     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
    #77     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
    #78     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
    #79     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
    #80     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
    #81     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:83:18)
    #82     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
    #83     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #84     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #85     _rootRun (dart:async/zone.dart:1180:38)
    #86     _CustomZone.run (dart:async/zone.dart:1077:19)
    #87     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
```

**Comment by sigurdm** [comment]
Fixed in https://github.com/dart-lang/pana/commit/4fd650676dfb95c59d7c630f4ce63ad092d19ab0
