### ISSUE TITLE
RangeError: End 1025 must not be greater than the number of characters in the file, 1024.

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#785]
I feel like we've fixed this before.

```
 "pub.analyzer.pana: Failed (v0.14.3) - tsumeshogi_solver/0.0.1

Error:
    RangeError: End 1025 must not be greater than the number of characters in the file, 1024.

Stack:
    #0      new _FileSpan (package:source_span/src/file.dart:354:7)
    #1      SourceFile.span (package:source_span/src/file.dart:92:12)
    #2      _analyzePackage.issueFromCodeProblem.<anonymous closure> (package:pana/src/create_report.dart:168:27)
    #3      _Issue.markdown (package:pana/src/create_report.dart:934:62)
    #4      _makeSummary.<anonymous closure>.<anonymous closure> (package:pana/src/create_report.dart:990:42)
    #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
    #6      SubListIterable.elementAt (dart:_internal/iterable.dart:267:22)
    #7      ListIterable.join (dart:_internal/iterable.dart:149:25)
    #8      _makeSummary.<anonymous closure> (package:pana/src/create_report.dart:1001:42)
    #9      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
    #10     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
    #11     _makeSummary (package:pana/src/create_report.dart:988:20)
    #12     _staticAnalysis (package:pana/src/create_report.dart:130:14)
    <asynchronous suspension>
    #13     createReport (package:pana/src/create_report.dart:54:11)
    <asynchronous suspension>
    #14     PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:178:21)
    <asynchronous suspension>
    #15     PackageAnalyzer.inspectPackage.<anonymous closure>.<anonymous closure> (package:pana/src/package_analyzer.dart:71:22)
    <asynchronous suspension>
    #16     PackageAnalyzer.inspectPackage.<anonymous closure>.<anonymous closure> (package:pana/src/package_analyzer.dart)
    #17     withTempDir (package:pana/src/download_utils.dart:245:20)
    <asynchronous suspension>
    #18     PackageAnalyzer.inspectPackage.<anonymous closure> (package:pana/src/package_analyzer.dart:68:14)
    #19     _rootRun (dart:async/zone.dart:1190:13)
    #20     _CustomZone.run (dart:async/zone.dart:1093:19)
    #21     _runZoned (dart:async/zone.dart:1630:10)
    #22     runZoned (dart:async/zone.dart:1550:10)
    #23     withLogger (package:pana/src/logging.dart:13:70)
    #24     PackageAnalyzer.inspectPackage (package:pana/src/package_analyzer.dart:66:12)
    #25     AnalyzerJobProcessor.process.analyze (package:pub_dev/analyzer/pana_runner.dart:76:31)
    <asynchronous suspension>
    #26     AnalyzerJobProcessor.process.analyze (package:pub_dev/analyzer/pana_runner.dart)
    #27     AnalyzerJobProcessor.process (package:pub_dev/analyzer/pana_runner.dart:102:30)
    <asynchronous suspension>
    #28     JobProcessor._runOneJob (package:pub_dev/job/job.dart:72:26)
    <asynchronous suspension>
    #29     JobProcessor.run (package:pub_dev/job/job.dart:52:28)
    <asynchronous suspension>
    #30     JobMaintenance.run (package:pub_dev/job/job.dart:115:18)
    #31     _workerMain.<anonymous closure> (package:pub_dev/service/entrypoint/analyzer.dart:96:26)
    #32     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #33     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #34     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #35     _rootRunUnary (dart:async/zone.dart:1198:47)
    #36     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #37     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
    #39     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
    #40     Future._completeWithValue (dart:async/future_impl.dart:529:5)
    #41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
    #42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
    #43     PopularityStorage.init (package:pub_dev/shared/popularity_storage.dart)
    #44     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #45     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #46     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #47     _rootRunUnary (dart:async/zone.dart:1198:47)
    #48     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #49     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #50     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
    #51     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
    #52     Future._completeWithValue (dart:async/future_impl.dart:529:5)
    #53     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
    #54     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
    #55     PopularityStorage.fetch (package:pub_dev/shared/popularity_storage.dart)
    #56     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #57     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #58     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #59     _rootRunUnary (dart:async/zone.dart:1198:47)
    #60     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #61     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #62     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
```

**Comment by isoos** [comment]
We did fix it, but it hasn't been released yet: https://github.com/dart-lang/pana/pull/783
