### ISSUE TITLE
Receiver: null Tried calling: where(Closure: (CodeProblem) => bool)

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#827]
```
Receiver: null Tried calling: where(Closure: (CodeProblem) => bool)
at Object.noSuchMethod (native)
at _analyzePackage (package:pana/src/create_report.dart:186)
at _staticAnalysis (package:pana/src/create_report.dart:104)
at createReport (package:pana/src/create_report.dart:60)
at PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:179)
at PackageAnalyzer.inspectPackage.<fn>.<fn> (package_analyzer.dart:71)
at PackageAnalyzer.inspectPackage.<fn>.<fn> (unknown location)
at withTempDir (package:pana/src/download_utils.dart:245)
at PackageAnalyzer.inspectPackage.<fn> (package_analyzer.dart:68)
at _rootRun (native)
at _CustomZone.run (native)
at _runZoned (native)
at runZoned (native)
at withLogger (package:pana/src/logging.dart:13)
at PackageAnalyzer.inspectPackage (package:pana/src/package_analyzer.dart:66)
```

**Comment by jonasfj** [comment]
Updated:
```
pub.analyzer.pana: Failed (v0.14.10) - pointycastle/3.0.0-nullsafety.2

Error:
    NoSuchMethodError: The method 'where' was called on null.
    Receiver: null
    Tried calling: where(Closure: (CodeProblem) => bool)

Stack:
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
    #1      _analyzePackage (package:pana/src/create_report.dart:186:14)
    <asynchronous suspension>
    #2      _staticAnalysis (package:pana/src/create_report.dart:104:32)
    #3      createReport (package:pana/src/create_report.dart:60:11)
    <asynchronous suspension>
    #4      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:179:21)
    <asynchronous suspension>
    #5      PackageAnalyzer.inspectPackage.<anonymous closure>.<anonymous closure> (package:pana/src/package_analyzer.dart:71:22)
    <asynchronous suspension>
    #6      PackageAnalyzer.inspectPackage.<anonymous closure>.<anonymous closure> (package:pana/src/package_analyzer.dart)
    #7      withTempDir (package:pana/src/download_utils.dart:245:20)
    <asynchronous suspension>
    #8      PackageAnalyzer.inspectPackage.<anonymous closure> (package:pana/src/package_analyzer.dart:68:14)
    #9      _rootRun (dart:async/zone.dart:1190:13)
    #10     _CustomZone.run (dart:async/zone.dart:1093:19)
    #11     _runZoned (dart:async/zone.dart:1630:10)
    #12     runZoned (dart:async/zone.dart:1550:10)
    #13     withLogger (package:pana/src/logging.dart:13:70)
    #14     PackageAnalyzer.inspectPackage (package:pana/src/package_analyzer.dart:66:12)
    #15     AnalyzerJobProcessor.process.analyze.<anonymous closure> (package:pub_dev/analyzer/pana_runner.dart:78:35)
    #16     withToolEnv (package:pub_dev/shared/tool_env.dart:41:20)
    <asynchronous suspension>
    #17     AnalyzerJobProcessor.process.analyze (package:pub_dev/analyzer/pana_runner.dart:71:20)
    #18     AnalyzerJobProcessor.process (package:pub_dev/analyzer/pana_runner.dart:105:30)
    <asynchronous suspension>
    #19     JobProcessor._runOneJob (package:pub_dev/job/job.dart:73:26)
    <asynchronous suspension>
    #20     JobProcessor.run (package:pub_dev/job/job.dart:53:28)
    <asynchronous suspension>
    #21     JobMaintenance.run (package:pub_dev/job/job.dart:116:18)
    #22     _workerMain.<anonymous closure> (package:pub_dev/service/entrypoint/analyzer.dart:79:26)
    #23     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #24     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #25     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #26     _rootRunUnary (dart:async/zone.dart:1198:47)
    #27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #28     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
    #30     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
    #31     Future._completeWithValue (dart:async/future_impl.dart:529:5)
    #32     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
    #33     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
    #34     PopularityStorage.init (package:pub_dev/shared/popularity_storage.dart)
    #35     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #36     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #37     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #38     _rootRunUnary (dart:async/zone.dart:1198:47)
    #39     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #40     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #41     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
    #42     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
    #43     Future._completeWithValue (dart:async/future_impl.dart:529:5)
    #44     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
    #45     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
    #46     PopularityStorage.fetch (package:pub_dev/shared/popularity_storage.dart)
    #47     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #48     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #49     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #50     _rootRunUnary (dart:async/zone.dart:1198:47)
```
