### ISSUE TITLE
pub.analyzer.pana: Failed (v0.15.4) - ffigen/2.5.0-beta.1

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#866]
```
pub.analyzer.pana: Failed (v0.15.4) - ffigen/2.5.0-beta.1

Error:
    Invalid argument(s): Provided content does not align with expectations.
    `No dart files found at: /tmp/pana_VPIXHM/lib`

Stack:
    #0      parseCodeProblem (package:pana/src/code_problem.dart:52:5)
    #1      PackageContext.staticAnalysis.<anonymous closure> (package:pana/src/package_context.dart:121:23)
    #2      MappedIterator.moveNext (dart:_internal/iterable.dart:389:20)
    #3      WhereIterator.moveNext (dart:_internal/iterable.dart:435:22)
    #4      SetMixin.addAll (dart:collection/set.dart:57:23)
    #5      new LinkedHashSet.of (dart:collection/linked_hash_set.dart:111:27)
    #6      Iterable.toSet (dart:core/iterable.dart:376:21)
    #7      PackageContext.staticAnalysis (package:pana/src/package_context.dart:123:12)
    <asynchronous suspension>
    #8      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
    <asynchronous suspension>
 ```

**Comment by isoos** [comment]
I think this has been fixed via #874 and/or #875. Current pub.dev analysis shows actual issues in the report.
