### ISSUE TITLE
type '_InvalidCollectionElement' is not a subtype of type 'Expression' in type cast

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#923]
Likely an analyzer issue.
```
pub.analyzer.pana: Failed (v0.18.2) - wialon/1.0.1+1

Error:
    type '_InvalidCollectionElement' is not a subtype of type 'Expression' in type cast

Stack:
    #0      StackImpl.popList (package:_fe_analyzer_shared/src/parser/stack_listener.dart:578:25)
    #1      AstBuilder.popTypedList (package:analyzer/src/fasta/ast_builder.dart:3686:11)
    #2      AstBuilder.handleLiteralList (package:analyzer/src/fasta/ast_builder.dart:3017:22)
    #3      Parser.parseLiteralListSuffix (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5524:14)
    #4      Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5333:14)
    #5      Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5195:12)
    #6      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4784:13)
    #7      Parser._parsePrecedenceExpressionLoop (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4833:17)
    #8      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4802:12)
    #9      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4725:13)
    #10     Parser.parseExpressionStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4690:13)
    #11     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6579:16)
    #12     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4486:14)
    #13     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4476:20)
    #14     Parser.parseBlock (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6972:15)
    #15     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4497:14)
    #16     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4476:20)
    #17     Parser.parseIfStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6670:13)
    #18     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4513:14)
    #19     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4476:20)
    #20     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4381:15)
    #21     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3910:15)
    #22     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3723:15)
    #23     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3382:15)
    #24     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1999:13)
    #25     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1957:14)
    #26     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
    #27     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
    #28     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
    #29     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:195:32)
    #30     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:191:12)
    #31     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:597:23)
    #32     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:403:12)
    #33     FileState._getUnlinkedBytes (package:analyzer/src/dart/analysis/file_state.dart:542:16)
    #34     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:447:17)
    #35     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:858:12)
    #36     FileTracker.getFile (package:analyzer/src/dart/analysis/file_tracker.dart:151:21)
    #37     AnalysisDriver.parseFileSync2 (package:analyzer/src/dart/analysis/driver.dart:1237:35)
    #38     AnalysisSessionImpl.getParsedUnit2 (package:analyzer/src/dart/analysis/session.dart:147:20)
    #39     _parsedUnitFromUri (package:pana/src/tag_detection.dart:184:38)
    #40     LibraryGraph.directSuccessors.<anonymous closure> (package:pana/src/tag_detection.dart:243:20)
    #41     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
    #42     LibraryGraph.directSuccessors (package:pana/src/tag_detection.dart:221:19)
    #43     _PathFinder.findPath (package:pana/src/tag_detection.dart:140:24)
    #44     _PathFinder.findViolation (package:pana/src/tag_detection.dart:152:41)
    #45     _SdkViolationFinder.findSdkViolation (package:pana/src/tag_detection.dart:658:38)
    #46     Tagger.sdkTags (package:pana/src/tag_detection.dart:792:20)
    #47     PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:177:16)
    <asynchronous suspension>
    #48     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
    <asynchronous suspension>
```

**Comment by jonasfj** [comment]
Duplicate of https://github.com/dart-lang/pana/issues/923
